// cpu_65c02 (new GameKing 65C02 core) under the r65c02 harness stimulus.
//
// Divergence-test companion to module_tests/r65c02: identical memory image
// (module_tests/r65c02/build/r65_mem_init.hex), identical stimulus timeline
// (reset for cycles 0..3, 8-cycle IRQ window at +IRQPULSE, 8-cycle NMI window
// at +NMIPULSE, +TOTAL cycles) and the same 22-column trace schema:
//   CYCLE,PC,SP,P_N,P_V,P_R,P_B,P_D,P_I,P_Z,P_C,Y,X,A,ADDR,DI,DO,RW,NMI_N,IRQ_N,SYNC,SYNC_IRQ
// so the CSV can be diffed field-for-field against r65c02/build/verilog_trace.csv.
//
// DUT mapping (cpu_65c02 is a different design family, not a port):
//   * clk  = 10 ns test clock; ce tied high => one bus access per posedge,
//     same effective model as the R65C02 bench's enable(1'b1).
//   * rdy  = 1 (wait-state behavior is a separate test item).
//   * reset= active-HIGH synchronous: 1 for cycles 0..3 (mirrors the
//     R65C02 bench's 4-cycle active-low window).
//   * stall/ce_n tied low; stp_nop=1 (Apple II has no power switch);
//     savestate bus tied off (no restore feature in this machine).
//   * Internal registers read via hierarchical refs (core has no Regs port):
//     reg_pc/reg_s/fl_*/reg_y/x/a. P_R and P_B are hardwired 1 in this core
//     (reg_p = {N,V,1,1,D,I,Z,C}); the comparator skips P_B by convention.
//   * SYNC_IRQ is emitted as (sync && int_seq): int_seq=int_active stays high
//     through the whole interrupt sequence in this core, so the AND marks the
//     interrupt-injected fetch rows, approximating R65C02's sync_irq.
//
// Memory model: combinational read din = mem[addr]; a write commits at the
// posedge where the registered we strobe is high (same convention as the
// R65C02 bench's !nwe commit).
//
// Output: module_tests/cpu_65c02/build/r65_trace.csv (CWD = repo root).

`timescale 1ns/1ps

module cpu65_r65_tb;
   reg clk = 0;
   // DUT reset is active-HIGH, synchronous.
   reg reset_sig = 0;
   // Set once stimulus has begun; keeps the write-back from firing on the
   // pre-stimulus posedge when DUT outputs are still at their init values.
   reg sim_go = 0;
   reg irq_n = 1;
   reg nmi_n = 1;

   wire [15:0] addr;
   wire [7:0] din;
   wire [7:0] dout;
   wire we;
   wire sync;
   wire int_seq;
   wire vector_pull;
   wire rti_done;
   wire in_wai;
   wire in_stp;
   wire [63:0] ss_rdata;

   integer irq_pulse = 0;
   integer nmi_pulse = 0;
   integer total_cycles = 0;

   // Single 64K image (pattern base + program + vectors), generated by the
   // r65c02 harness's perl generator.
   reg [7:0] mem [0:65535];

   always #5 clk = ~clk;

   cpu_65c02 dut (
      .clk(clk),
      .ce(1'b1),
      .ce_n(1'b0),
      .reset(reset_sig),
      .stall(1'b0),
      .irq_n(irq_n),
      .nmi_n(nmi_n),
      .rdy(1'b1),
      .stp_nop(1'b1),
      .addr(addr),
      .dout(dout),
      .din(din),
      .we(we),
      .sync(sync),
      .vector_pull(vector_pull),
      .int_seq(int_seq),
      .rti_done(rti_done),
      .in_wai(in_wai),
      .in_stp(in_stp),
      .ss_addr(10'd0),
      .ss_wdata(64'd0),
      .ss_wren(1'b0),
      .ss_rdata(ss_rdata)
   );

   // Keep the status outputs referenced so Verilator doesn't optimize them
   // away before we can inspect them in a future debug run.
   wire unused_ok = &{1'b0, vector_pull, rti_done, in_wai, in_stp, ss_rdata};

   // Combinational read: the DUT presents the address it wants to see.
   assign din = mem[addr];

   // Commit writes at the posedge where the (registered) we strobe is high.
   always @(posedge clk) begin
      if (sim_go && we)
         mem[addr] <= dout;
   end

   initial begin
      $value$plusargs("IRQPULSE=%d", irq_pulse);
      $value$plusargs("NMIPULSE=%d", nmi_pulse);
      $value$plusargs("TOTAL=%d", total_cycles);
      if (total_cycles == 0) total_cycles = 4000;
      $readmemh("module_tests/r65c02/build/r65_mem_init.hex", mem);
   end

   task automatic apply_stimulus(input integer cycle);
      begin
         reset_sig = (cycle < 4) ? 1'b1 : 1'b0;
         irq_n     = (irq_pulse != 0 && cycle >= irq_pulse && cycle < irq_pulse + 8) ? 1'b0 : 1'b1;
         nmi_n     = (nmi_pulse != 0 && cycle >= nmi_pulse && cycle < nmi_pulse + 8) ? 1'b0 : 1'b1;
      end
   endtask

   initial begin
      integer trace_output;
      integer cycle;

      trace_output = $fopen("module_tests/cpu_65c02/build/r65_trace.csv", "w");
      if (!trace_output) $fatal(1, "could not open cpu_65c02 r65 trace output");
      $fdisplay(trace_output, "CYCLE,PC,SP,P_N,P_V,P_R,P_B,P_D,P_I,P_Z,P_C,Y,X,A,ADDR,DI,DO,RW,NMI_N,IRQ_N,SYNC,SYNC_IRQ");

      for (cycle = 0; cycle < total_cycles; cycle = cycle + 1) begin
         @(negedge clk);
         sim_go = 1;
         apply_stimulus(cycle);
         @(posedge clk);
         #1;

         $fdisplay(trace_output, "%0d,%04X,%02X,%b,%b,%b,%b,%b,%b,%b,%b,%02X,%02X,%02X,%04X,%02X,%02X,%b,%b,%b,%b,%b",
            cycle,
            dut.reg_pc, dut.reg_s,
            dut.fl_n, dut.fl_v, 1'b1, 1'b1, dut.fl_d, dut.fl_i, dut.fl_z, dut.fl_c,
            dut.reg_y, dut.reg_x, dut.reg_a,
            addr, din, dout, !we, nmi_n, irq_n, sync, (sync && int_seq));
      end

      $fclose(trace_output);
      $display("cpu_65c02 r65-stimulus trace complete (cycles=%0d irq_pulse=%0d nmi_pulse=%0d)",
         total_cycles, irq_pulse, nmi_pulse);
      $finish;
   end
endmodule
