// R65C02 (VHDL golden) vs R65C02 (Verilog candidate) cycle-equivalence testbench.
//
// Mirror of r65c02_vhdl_tb.vhd. Instantiates the Verilog R65C02 from
// rtl/R65Cx2.sv with enable tied high. Same memory model, stimulus timelines,
// and trace schema as the VHDL bench:
//   CYCLE,PC,SP,P_N,P_V,P_R,P_B,P_D,P_I,P_Z,P_C,Y,X,A,ADDR,DI,DO,RW,NMI_N,IRQ_N,SYNC,SYNC_IRQ
//
// Memory model: one 64K image (base pattern + directed program + vectors) from
// build/r65_mem_init.hex, generated by build/gen_mem_array.pl. The DUT's addr
// output is the live fetch/operand address; di = mem[addr]; a write commits at
// the posedge where the registered nwe strobe is low.
//
// Regs layout (from rtl/R65Cx2.sv): {PC[15:0], 8'b00000001, S, N,V,R,B,D,I,Z,C, Y, X, A}
// so PC=[63:48], S=[39:32], P byte=[31:24] with N=31 V=30 R=29 B=28 D=27 I=26 Z=25 C=24,
// Y=[23:16], X=[15:8], A=[7:0]. P is emitted per-bit; B is never driven by the core
// (VHDL 'U', Verilog 0) and the comparator skips it.
//
// reset is ACTIVE-LOW on this DUT (0 = in reset); held low for cycles 0..3,
// mirroring the t65 bench's 4-cycle active-high reset window.
//
// Stimulus plusargs (identical values must be passed to both benches):
//   +IRQPULSE=<cycle>  irq_n low for 8 cycles from <cycle> (0 = disabled)
//   +NMIPULSE=<cycle>  nmi_n low for 8 cycles from <cycle> (0 = disabled)
//   (The DUT samples the interrupt lines only on non-fetch/non-branch-taken
//    cycles, so a 1-cycle pulse can be missed depending on instruction phase.)
//   +TOTAL=<cycles>    trace length (default 4000)
// A pulse set at cycle N is sampled by the DUT at posedge N.
//
// Output: module_tests/r65c02/build/verilog_trace.csv (CWD = repo root).

`timescale 1ns/1ps

module r65c02_verilog_tb;
   reg clk = 0;
   // DUT input is named `reset` and is active-low.
   reg reset_sig = 0;
   // Set once stimulus has begun; keeps the write-back from firing on the
   // pre-stimulus posedge when DUT outputs are still at their init values.
   reg sim_go = 0;
   reg irq_n = 1;
   reg nmi_n = 1;

   wire [15:0] addr;
   wire [7:0] di;
   wire [7:0] dout;
   wire nwe;
   wire sync;
   wire sync_irq;
   wire [63:0] regs;

   integer irq_pulse = 0;
   integer nmi_pulse = 0;
   integer total_cycles = 0;

   // Single 64K image (pattern base + program + vectors).
   reg [7:0] mem [0:65535];

   always #5 clk = ~clk;

   R65C02 dut (
      .reset(reset_sig),
      .clk(clk),
      .enable(1'b1),
      .nmi_n(nmi_n),
      .irq_n(irq_n),
      .di(di),
      .dout(dout),
      .addr(addr),
      .nwe(nwe),
      .sync(sync),
      .sync_irq(sync_irq),
      .Regs(regs)
   );

   // Combinational read: the DUT presents the address it wants to see.
   assign di = mem[addr];

   // Commit writes at the posedge where the (registered) nwe strobe is low.
   always @(posedge clk) begin
      if (sim_go && !nwe)
         mem[addr] <= dout;
   end

   initial begin
      $value$plusargs("IRQPULSE=%d", irq_pulse);
      $value$plusargs("NMIPULSE=%d", nmi_pulse);
      $value$plusargs("TOTAL=%d", total_cycles);
      if (total_cycles == 0) total_cycles = 4000;
      $readmemh("module_tests/r65c02/build/r65_mem_init.hex", mem);
   end

   task automatic apply_stimulus(input integer cycle);
      begin
         reset_sig = (cycle < 4) ? 1'b0 : 1'b1;
         irq_n     = (irq_pulse != 0 && cycle >= irq_pulse && cycle < irq_pulse + 8) ? 1'b0 : 1'b1;
         nmi_n     = (nmi_pulse != 0 && cycle >= nmi_pulse && cycle < nmi_pulse + 8) ? 1'b0 : 1'b1;
      end
   endtask

   initial begin
      integer trace_output;
      integer cycle;

      trace_output = $fopen("module_tests/r65c02/build/verilog_trace.csv", "w");
      if (!trace_output) $fatal(1, "could not open Verilog trace output");
      $fdisplay(trace_output, "CYCLE,PC,SP,P_N,P_V,P_R,P_B,P_D,P_I,P_Z,P_C,Y,X,A,ADDR,DI,DO,RW,NMI_N,IRQ_N,SYNC,SYNC_IRQ");

      for (cycle = 0; cycle < total_cycles; cycle = cycle + 1) begin
         @(negedge clk);
         sim_go = 1;
         apply_stimulus(cycle);
         @(posedge clk);
         #1;

         $fdisplay(trace_output, "%0d,%04X,%02X,%b,%b,%b,%b,%b,%b,%b,%b,%02X,%02X,%02X,%04X,%02X,%02X,%b,%b,%b,%b,%b",
            cycle,
            regs[63:48], regs[39:32],
            regs[31], regs[30], regs[29], regs[28], regs[27], regs[26], regs[25], regs[24],
            regs[23:16], regs[15:8], regs[7:0],
            addr, di, dout, nwe, nmi_n, irq_n, sync, sync_irq);
      end

      $fclose(trace_output);
      $display("R65C02 Verilog trace complete (cycles=%0d irq_pulse=%0d nmi_pulse=%0d)",
         total_cycles, irq_pulse, nmi_pulse);
      $finish;
   end
endmodule
