-- R65C02 (VHDL golden) cycle-equivalence testbench.
--
-- Mirror of r65c02_verilog_tb.sv. Instantiates the VHDL R65C02 from
-- ../../../Apple-II_MiSTer_newsdee/rtl/R65Cx2.vhd with enable tied high.
-- Same memory model, stimulus timelines, and trace schema as the Verilog
-- bench:
--   CYCLE,PC,SP,P_N,P_V,P_R,P_B,P_D,P_I,P_Z,P_C,Y,X,A,ADDR,DI,DO,RW,NMI_N,IRQ_N,SYNC,SYNC_IRQ
--
-- Memory model: one 64K image (base pattern + directed program + vectors)
-- from build/r65_mem_array.vhd (MEM_INIT), generated by build/gen_mem_array.pl.
-- The DUT's addr output is the live fetch/operand address; di = mem[addr]; a
-- write commits at the rising edge where the registered nwe strobe is low.
--
-- Regs layout (identical in both languages):
--   {PC(16), "00000001", S(8), N,V,R,B,D,I,Z,C, Y(8), X(8), A(8)}
-- so PC=(63:48), S=(39:32), P byte=(31:24) with N=31 V=30 R=29 B=28 D=27
-- I=26 Z=25 C=24, Y=(23:16), X=(15:8), A=(7:0). P is emitted per-bit; B is
-- never driven by the core ('U' here, 0 in Verilog) and the comparator skips
-- it. Meta values (U/X) are emitted verbatim; the comparator skips them.
--
-- reset is ACTIVE-LOW on this DUT (0 = in reset); held low for cycles 0..3,
-- mirroring the t65 bench's 4-cycle window and the Verilog TB's init value.
--
-- Stimulus (must match the Verilog TB plusargs exactly):
--   irq_n low for cycles [IRQ_PULSE, IRQ_PULSE+8)
--   nmi_n low for cycles [NMI_PULSE, NMI_PULSE+8)
--   (The DUT samples the interrupt lines only on non-fetch/non-branch-taken
--    cycles, so a 1-cycle pulse can be missed depending on instruction phase.)
-- A pulse set at cycle N is sampled by the DUT at posedge N.

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use ieee.std_logic_textio.all;
use std.textio.all;
use work.r65_mem_array.all;

entity r65c02_vhdl_tb is
  generic (
    TOTAL_CYCLES : integer := 4000;
    IRQ_PULSE    : integer := 730;   -- 0 = disabled
    NMI_PULSE    : integer := 768;   -- 0 = disabled
    TRACE_FILE   : string  := "module_tests/r65c02/build/vhdl_trace.csv"
  );
end entity;

architecture test of r65c02_vhdl_tb is
  signal clk     : std_logic := '0';
  signal res_n   : std_logic := '0';  -- active-low reset, in reset at t=0
  signal irq_n   : std_logic := '1';
  signal nmi_n   : std_logic := '1';
  -- Set at the first falling edge (mirrors the Verilog TB sim_go guard so the
  -- write commit cannot fire on the pre-stimulus rising edge).
  signal sim_go  : std_logic := '0';

  signal addr    : unsigned(15 downto 0);
  signal di      : unsigned(7 downto 0);
  signal do_sig  : unsigned(7 downto 0);
  signal nwe     : std_logic;
  signal sync    : std_logic;
  signal sync_irq: std_logic;
  signal regs    : std_logic_vector(63 downto 0);

  -- Single 64K image, static init from the generated package. Only the write
  -- commit process drives it afterwards (GHDL mcode corrupts nonblocking
  -- array updates when two processes drive the same array — see t65_vhdl_tb).
  signal mem : mem_vec_t := MEM_INIT;

  -- VHDL-93 std_logic_1164 has no all_defined; local equivalent.
  function all_def(s : std_logic_vector) return boolean is
  begin
    for k in s'range loop
      if s(k) /= '0' and s(k) /= '1' then return false; end if;
    end loop;
    return true;
  end function all_def;

  -- VHDL-93 numeric_std has no to_hstring and no std_logic_vector->unsigned
  -- conversion; local meta-safe equivalent (meta bytes emit all '?').
  function hex_of(v : std_logic_vector) return string is
    variable n : integer := v'length / 4;
    variable s : string(1 to n);
    variable nib : std_logic_vector(3 downto 0);
  begin
    if not all_def(v) then
      for i in 1 to n loop s(i) := '?'; end loop;
      return s;
    end if;
    for i in 1 to n loop
      -- downto vector: leftmost nibble starts at v'left and moves down.
      nib := v(v'left - 4 * (i - 1) downto v'left - 4 * (i - 1) - 3);
      case nib is
        when "0000" => s(i) := '0';
        when "0001" => s(i) := '1';
        when "0010" => s(i) := '2';
        when "0011" => s(i) := '3';
        when "0100" => s(i) := '4';
        when "0101" => s(i) := '5';
        when "0110" => s(i) := '6';
        when "0111" => s(i) := '7';
        when "1000" => s(i) := '8';
        when "1001" => s(i) := '9';
        when "1010" => s(i) := 'A';
        when "1011" => s(i) := 'B';
        when "1100" => s(i) := 'C';
        when "1101" => s(i) := 'D';
        when "1110" => s(i) := 'E';
        when others => s(i) := 'F';
      end case;
    end loop;
    return s;
  end function hex_of;

begin
  clk <= not clk after 5 ns;

  dut : entity work.R65C02
    port map (
      reset    => res_n,
      clk      => clk,
      enable   => '1',
      nmi_n    => nmi_n,
      irq_n    => irq_n,
      di       => di,
      do       => do_sig,
      addr     => addr,
      nwe      => nwe,
      sync     => sync,
      sync_irq => sync_irq,
      Regs     => regs
    );

  -- Combinational read: the DUT presents the address it wants to see. Guard
  -- against meta addresses (GHDL rejects 'U' array indices); during reset the
  -- DUT drives $FFFC so this path is only a safety net.
  process(addr, mem)
  begin
    if all_def(std_logic_vector(addr)) then
      di <= unsigned(mem(to_integer(unsigned(addr))));
    else
      di <= x"00";
    end if;
  end process;

  -- Commit writes at the rising edge where the (registered) nwe strobe is low.
  process(clk)
  begin
    if rising_edge(clk) then
      if sim_go = '1' and nwe = '0' and all_def(std_logic_vector(addr)) then
        mem(to_integer(unsigned(addr))) <= std_logic_vector(do_sig);
      end if;
    end if;
  end process;

  stimulus : process
    file trace_output : text open write_mode is TRACE_FILE;
    variable trace_line : line;
    variable total : integer;
  begin
    total := TOTAL_CYCLES;

    write(trace_line, string'("CYCLE,PC,SP,P_N,P_V,P_R,P_B,P_D,P_I,P_Z,P_C,Y,X,A,ADDR,DI,DO,RW,NMI_N,IRQ_N,SYNC,SYNC_IRQ"));
    writeline(trace_output, trace_line);

    for cycle in 0 to total - 1 loop
      wait until falling_edge(clk);

      if cycle = 0 then sim_go <= '1'; end if;
      if cycle < 4 then res_n <= '0'; else res_n <= '1'; end if;
      if IRQ_PULSE /= 0 and cycle >= IRQ_PULSE and cycle < IRQ_PULSE + 8 then
        irq_n <= '0';
      else
        irq_n <= '1';
      end if;
      if NMI_PULSE /= 0 and cycle >= NMI_PULSE and cycle < NMI_PULSE + 8 then
        nmi_n <= '0';
      else
        nmi_n <= '1';
      end if;

      wait until rising_edge(clk);
      wait for 1 ns;

      write(trace_line, cycle);
      write(trace_line, string'(",")); write(trace_line, hex_of(regs(63 downto 48)));
      write(trace_line, string'(",")); write(trace_line, hex_of(regs(39 downto 32)));
      write(trace_line, string'(",")); write(trace_line, regs(31)); -- P_N
      write(trace_line, string'(",")); write(trace_line, regs(30)); -- P_V
      write(trace_line, string'(",")); write(trace_line, regs(29)); -- P_R
      write(trace_line, string'(",")); write(trace_line, regs(28)); -- P_B (meta in VHDL)
      write(trace_line, string'(",")); write(trace_line, regs(27)); -- P_D
      write(trace_line, string'(",")); write(trace_line, regs(26)); -- P_I
      write(trace_line, string'(",")); write(trace_line, regs(25)); -- P_Z
      write(trace_line, string'(",")); write(trace_line, regs(24)); -- P_C
      write(trace_line, string'(",")); write(trace_line, hex_of(regs(23 downto 16)));
      write(trace_line, string'(",")); write(trace_line, hex_of(regs(15 downto 8)));
      write(trace_line, string'(",")); write(trace_line, hex_of(regs(7 downto 0)));
      if all_def(std_logic_vector(addr)) then
        write(trace_line, string'(",")); write(trace_line, hex_of(std_logic_vector(addr)));
      else
        write(trace_line, string'( ",????"));
      end if;
      write(trace_line, string'(",")); write(trace_line, hex_of(std_logic_vector(di)));
      write(trace_line, string'(",")); write(trace_line, hex_of(std_logic_vector(do_sig)));
      write(trace_line, string'(",")); write(trace_line, nwe);
      write(trace_line, string'(",")); write(trace_line, nmi_n);
      write(trace_line, string'(",")); write(trace_line, irq_n);
      write(trace_line, string'(",")); write(trace_line, sync);
      write(trace_line, string'(",")); write(trace_line, sync_irq);
      writeline(trace_output, trace_line);
    end loop;

    report "R65C02 VHDL trace complete (cycles=" & integer'image(total) & ")" severity note;
    -- No std.env in VHDL-93; the runner's --stop-time ends the simulation.
    wait;
  end process;
end architecture;
