// tb_burst_probe.sv
//
// Measures the raw VIDEO bitstream during horizontal blanking so the
// composite-encoder burst window (apple_composite BURST_START/BURST_LEN,
// in samples after the HSYNC falling edge) can be set from the core's
// actual timing instead of guessed.
//
// What it reports (per sampled line):
//   - HBL duration in machine cycles
//   - VIDEO run-length pattern inside the HBL window
//   - the full-rate (0101...) toggle region after the HSYNC fall:
//     start/length in samples after the HSYNC falling edge
//
// HSYNC is derived the same way the level-2 wrapper does it
// (130 cycles after HBL rise, width 68) so the coordinate system is
// the one the encoder will use.
//
// The VIDEO-during-blanking pattern is generated by the timing
// generator + video ROM sync row and does not depend on the CPU or
// screen contents, so this probe ties the core's I/O/RAM paths to
// constants (no keyboard, no disk, ram_do = 0).  machine_ce MUST be 1
// (core gates all machine state on it).
//
// Build (from unit_tests/level_2/; the verilator binary is
// C:\msys64\ucrt64\bin\verilator_bin.exe, VERILATOR_ROOT set to
// C:\msys64\ucrt64\share\verilator):
//   <verilator> --binary --timing -O3 --x-assign fast --x-initial fast \
//     -Wno-fatal -Wno-TIMESCALEMOD --timescale-override 1ns/1ps \
//     --top-module tb_burst_probe -Mdir build/burst_probe_obj_dir \
//     tb_burst_probe.sv <apple2.v timing_generator.v video_generator.v \
//     rom.v ramcard.v keyboard.v + both cpu dirs, all under ../../rtl/>
// Run (CWD = repo root; ROM paths are CWD-relative):
//   ./unit_tests/level_2/build/burst_probe_obj_dir/Vtb_burst_probe

`timescale 1ns/1ps

module tb_burst_probe;

  // 14.318 MHz master (35 ns half-period).
  reg clk = 1'b0;
  always #35 clk = ~clk;

  // ------------------------------------------------------------------
  // core inputs
  // ------------------------------------------------------------------
  reg         reset_sync  = 1'b1;
  reg  [15:0] ram_do      = 16'h0000;
  wire        w_video, w_hbl, w_vbl, w_col_line, w_text_mode;
  wire        w_clk_2m, w_pz, w_pzr, w_pzf, w_spk;
  wire        w_read_key;
  wire [15:0] w_addr;
  wire [17:0] w_ram_addr;
  wire [7:0]  w_ram_di;
  wire        w_ram_aux, w_ram_we, w_cpu_we;
  wire [7:0]  w_an, w_io_sel, w_dev_sel;
  wire        w_io_str, w_pdl, w_stb;

  // ~2 Hz flash clock (like the real board), 2^23 div.
  reg [22:0] flash_div = 23'b0;
  always @(posedge clk) flash_div <= flash_div + 1'b1;

  // 60 Hz IRQ pulse per VBL rise (keeps the ROM's OS timers happy).
  reg [4:0] irq_cnt = 5'd0;
  reg       vbl_d   = 1'b0;
  always @(posedge clk) begin
    vbl_d <= w_vbl;
    if (w_vbl && !vbl_d) irq_cnt <= 5'd16;
    else if (irq_cnt != 5'd0) irq_cnt <= irq_cnt - 5'd1;
  end

  apple2 dut (
    .CLK_14M      (clk),
    .CLK_2M       (w_clk_2m),
    .PALMODE      (1'b0),
    .ROMSWITCH    (1'b0),
    .CPU_WAIT     (1'b0),
    .PHASE_ZERO   (w_pz),
    .PHASE_ZERO_R (w_pzr),
    .PHASE_ZERO_F (w_pzf),
    .FLASH_CLK    (flash_div[22]),
    .reset        (reset_sync),
    .cpu          (1'b1),
    .STALL        (1'b0),
    .ADDR         (w_addr),
    .ram_addr     (w_ram_addr),
    .D            (w_ram_di),
    .ram_do       (ram_do),
    .aux          (w_ram_aux),
    .PD           (8'h00),
    .CPU_WE       (w_cpu_we),
    .IRQ_n        (irq_n),
    .NMI_n        (1'b1),
    .ram_we       (w_ram_we),
    .VIDEO        (w_video),
    .COLOR_LINE   (w_col_line),
    .TEXT_MODE    (w_text_mode),
    .HBL          (w_hbl),
    .VBL          (w_vbl),
    .K            (8'h20),
    .READ_KEY     (w_read_key),
    .AKD          (1'b0),
    .AN           (w_an),
    .GAMEPORT     (8'h00),
    .PDL_STROBE   (w_pdl),
    .STB          (w_stb),
    .IO_SELECT    (w_io_sel),
    .DEVICE_SELECT(w_dev_sel),
    .IO_STROBE    (w_io_str),
    .ioctl_addr   (25'b0),
    .ioctl_data   (8'b0),
    .ioctl_index  (8'b0),
    .ioctl_download(1'b0),
    .ioctl_wr     (1'b0),
    .saturn_5_inslot(1'b0),
    .speaker      (w_spk),
    .machine_ce   (1'b1),
    .ss_wren      (1'b0),
    .ss_addr      (10'd0),
    .ss_wdata     (64'd0)
  );
  // IRQ_n low for 16 cycles per VBL rise (mirrors the tb_l2/mister wrapper:
  // irq_60hz_cnt 16 -> 0, IRQ_n = (cnt == 0)).
  wire irq_n = (irq_cnt == 5'd0);

  // ------------------------------------------------------------------
  // sampler: on each HBL rise, capture VIDEO/HBL for up to LINE_MAX cycles.
  // Coordinate system: cap_video[i] = VIDEO during the (i+1)th HBL-adjacent
  // cycle, i.e. i == the wrapper's hblank_cnt (0 = first HBL-high cycle),
  // matching the hsync coordinate system the encoder will use.
  // The capture runs through the following active video and is simply
  // restarted at the next HBL rise - the analysis only needs the HBL span.
  // ------------------------------------------------------------------
  localparam LINE_MAX = 1100;
  reg  hbl_d     = 1'b0;
  wire hbl_rise  = w_hbl & ~hbl_d;
  integer cap_len   = 0;
  integer cap_lines = 0;
  integer line_len  = 0;   // cycles from one HBL rise to the next
  reg        cap_video [0:LINE_MAX-1];
  reg        cap_hbl   [0:LINE_MAX-1];

  always @(posedge clk) begin
    hbl_d <= w_hbl;
    if (hbl_rise) begin
      if (cap_len != 0) line_len = cap_len;  // previous line's full length
      // cycle F (first HBL-high cycle, hblank_cnt=0)
      cap_video[0] <= w_video;
      cap_hbl[0]   <= w_hbl;
      cap_len     <= 1;
      cap_lines   <= cap_lines + 1;
    end else if (cap_len != 0 && cap_len < LINE_MAX) begin
      cap_video[cap_len] <= w_video;
      cap_hbl[cap_len]   <= w_hbl;
      cap_len <= cap_len + 1;
    end
  end

  // ------------------------------------------------------------------
  // analysis of the most recent captured line
  // ------------------------------------------------------------------
  // HSYNC per the level-2 wrapper: rise at 130 after HBL rise, width 68
  // -> the hs-fall cycle is at hblank_cnt = 198.  The decoder's burst
  // counter (hcnt) is 0 on the FIRST sample after the hs-fall cycle, so
  // hcnt = hblank_cnt - 199.  BURST_START/BURST_LEN are reported in hcnt
  // terms - the units the decoder (and the encoder) use.
  localparam HS_RISE = 130;
  localparam HS_WID  = 68;
  localparam HS_FALL = HS_RISE + HS_WID;  // 198, hblank_cnt of the hs-fall cycle
  localparam HCNT0   = HS_FALL + 1;       // hblank_cnt == 199 -> hcnt == 0

  // run-length encode the captured HBL window and report the toggle
  // region after HS_FALL.
  task automatic report_line;
    integer hbl_end;
    integer i, run_start, run_val, prev;
    integer tog_start, tog_end;
    begin
      // HBL span (first falling edge after rise).
      hbl_end = -1;
      for (i = 0; i < LINE_MAX; i = i + 1)
        if (cap_hbl[i] && !cap_hbl[i+1] && cap_hbl[i+1] !== 1'bx) begin
          hbl_end = i + 1;
          break;
        end
      if (hbl_end < 0) hbl_end = LINE_MAX;

      $display("LINE %0d: HBL cycles=%0d  line length=%0d (hcnt0 = %0d, HBL end hcnt = %0d, capture max %0d)",
               cap_lines, hbl_end, line_len, HCNT0, hbl_end - HCNT0, LINE_MAX);

      // run-length pattern of VIDEO inside [0, hbl_end)
      $display("  VIDEO runs inside HBL (start:len:val):");
      run_start = 0; run_val = cap_video[0];
      for (i = 1; i < hbl_end; i = i + 1) begin
        if (cap_video[i] !== cap_video[i-1]) begin
          $display("    %0d : %0d : %b", run_start, i - run_start, run_val);
          run_start = i; run_val = cap_video[i];
        end
      end
      $display("    %0d : %0d : %b", run_start, hbl_end - run_start, run_val);

      // sanity: the active region after the HBL span (line length 912 =
      // 352 HBL + 560 active)
      $display("  VIDEO runs in active [hbl_end..+560):");
      run_start = hbl_end; run_val = cap_video[hbl_end];
      for (i = hbl_end + 1; i < hbl_end + 560 && i < LINE_MAX; i = i + 1) begin
        if (cap_video[i] !== cap_video[i-1]) begin
          $display("    %0d : %0d : %b", run_start, i - run_start, run_val);
          run_start = i; run_val = cap_video[i];
        end
      end
      $display("    %0d : %0d : %b", run_start, (i < LINE_MAX ? i : hbl_end + 560) - run_start, run_val);

      // full-rate toggle region after the hs fall: consecutive cycles where
      // VIDEO changes every cycle, reported in decoder hcnt units (hcnt 0 =
      // the first sample after the hs-fall cycle).
      tog_start = -1; tog_end = -1;
      for (i = HCNT0; i < hbl_end; i = i + 1) begin
        if (cap_video[i] !== cap_video[i-1]) begin
          if (tog_start < 0) tog_start = i - 1;
          tog_end = i;
        end
        else if (tog_start >= 0 && (i - tog_start) > 1) begin
          // a non-toggle broke the run: keep the longest run seen
          if (i - 1 > tog_end) tog_end = i - 1;
          tog_start = -1;
        end
      end
      if (tog_start < 0)
        $display("  NO full-rate toggle region after hs fall (hcnt 0 = hblank_cnt %0d)", HCNT0);
      else
        $display("  TOGGLE region: hblank_cnt [%0d..%0d] ->  BURST_START=%0d  BURST_LEN=%0d (hcnt units)",
                 tog_start, tog_end, tog_start - HCNT0, tog_end - tog_start + 1);
      $display("  HBL ends at hblank_cnt %0d (hcnt %0d); clamp window must fit: BURST_START+BURST_LEN+16 <= %0d",
               hbl_end, hbl_end - HCNT0, hbl_end - HCNT0);
    end
  endtask

  // ------------------------------------------------------------------
  // main
  // ------------------------------------------------------------------
  initial begin
    // power-on reset
    reset_sync = 1'b1;
    repeat (200) @(posedge clk);
    reset_sync = 1'b0;

    // let the machine settle (~1 s of machine time), then sample lines.
    repeat (14_318_181 / 4) @(posedge clk);  // ~250 ms

    // capture and report 4 lines
    for (integer n = 0; n < 4; n = n + 1) begin
      wait (hbl_rise);
      // wait for the HBL span to end; its capture is then complete
      wait (!w_hbl);
      report_line;
    end

    $display("BURST_PROBE DONE");
    $finish;
  end

endmodule
