# Generates spram_const.vhd - a GHDL-safe, constant-array replacement for
# work.spram for the golden (VHDL) side of module_tests harnesses.
#
# WHY: GHDL 6.0.0 does not honor the ram_init_file attribute used by
# rtl/spram.vhd (golden sims would see an all-zero ROM), and this GHDL build
# has a codegen bug where signal assignments are silently dropped when a
# case-based function call occurs in the same loop (see spram_sim.vhd header
# and subagent_plan.md). The workaround is to embed the ROM bytes as a VHDL
# constant array: no file I/O, no case statements, no load loop.
#
# The emitted entity is named `spram` (same generics/ports as rtl/spram.vhd)
# and holds ALL harness ROMs in one concatenated constant array; the
# init_file generic selects the segment (string compare, no case).
#
# Usage (from anywhere):
#   powershell -NoProfile -ExecutionPolicy Bypass -File module_tests/shared/gen_spram_const.ps1
#
# Inputs  (newsdee .mif sources, read-only):
#   Apple-II_MiSTer_newsdee/rtl/roms/video2.mif    (8192 x 8)
#   Apple-II_MiSTer_newsdee/rtl/roms/keyboard.mif  (2048 x 8)
#   Apple-II_MiSTer_newsdee/rtl/roms/apple2e.mif   (16384 x 8)
# Output:
#   module_tests/shared/spram_const.vhd

param(
    [string]$OutFile = (Join-Path $PSScriptRoot 'spram_const.vhd')
)

$ErrorActionPreference = 'Stop'

$newsdeeRoot = (Resolve-Path (Join-Path $PSScriptRoot '..\..\..\Apple-II_MiSTer_newsdee')).Path

function Read-Mif([string]$Path, [string]$Name) {
    if (!(Test-Path $Path)) { throw "MIF not found: $Path" }
    $text = Get-Content $Path -Raw
    if ($text -notmatch 'CONTENT\s+BEGIN') { throw "${Name}: no CONTENT BEGIN in $Path" }
    $depthMatch = [regex]::Match($text, 'DEPTH\s*=\s*(\d+)')
    $expected = [int]$depthMatch.Groups[1].Value
    $bytes = New-Object System.Collections.Generic.List[uint32]
    $inContent = $false
    foreach ($line in ($text -split "`r?`n")) {
        $t = $line.Trim()
        if ($t -eq 'CONTENT BEGIN') { $inContent = $true; continue }
        if ($t -eq 'CONTENT END' -or $t -eq 'END;') { $inContent = $false; continue }
        if (-not $inContent) { continue }
        if ($t -eq '' -or $t.StartsWith('--')) { continue }
        # line form:  0000: 1C 22 2A ...;
        $m = [regex]::Match($t, '^[0-9A-Fa-f]+:\s*(.*?);?\s*$')
        if (-not $m.Success) { throw "${Name}: unparseable MIF line: $t" }
        foreach ($tok in ($m.Groups[1].Value -split '\s+' | Where-Object { $_ -ne '' })) {
            $bytes.Add([Convert]::ToByte($tok, 16))
        }
    }
    if ($bytes.Count -ne $expected) {
        throw "${Name}: $Path has $($bytes.Count) bytes, DEPTH says $expected"
    }
    return $bytes
}

$segments = @(
    @{ Name = 'video2';   Mif = 'video2.mif';   Words = 8192  },
    @{ Name = 'keyboard'; Mif = 'keyboard.mif'; Words = 2048  },
    @{ Name = 'apple2e';  Mif = 'apple2e.mif';  Words = 16384 }
)

$data = @{}
foreach ($s in $segments) {
    $data[$s.Name] = Read-Mif (Join-Path $newsdeeRoot "rtl\roms\$($s.Mif)") $s.Name
}

# Segment offsets
$offset = @{}
$base = 0
$total = 0
foreach ($s in $segments) {
    $offset[$s.Name] = $base
    $base += $s.Words
}
$total = $base

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('-- AUTO-GENERATED by gen_spram_const.ps1 - do not edit by hand.')
[void]$sb.AppendLine('-- GHDL-safe constant-array replacement for work.spram (see script header).')
[void]$sb.AppendLine('-- Segments (init_file selector -> offset):')
foreach ($s in $segments) {
    [void]$sb.AppendLine("--   ""rtl/roms/$($s.Mif)"" -> $($offset[$s.Name])  ($($s.Words) words)")
}
[void]$sb.AppendLine('library ieee;')
[void]$sb.AppendLine('use ieee.std_logic_1164.all;')
[void]$sb.AppendLine('use ieee.numeric_std.all;')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('entity spram is')
[void]$sb.AppendLine('    generic (')
[void]$sb.AppendLine('        addrbits  : integer := 9;')
[void]$sb.AppendLine('        databits  : integer := 7;')
[void]$sb.AppendLine('        init_file : string  := ""')
[void]$sb.AppendLine('    );')
[void]$sb.AppendLine('    port (')
[void]$sb.AppendLine('        address : in  std_logic_vector(addrbits-1 downto 0);')
[void]$sb.AppendLine('        clock   : in  std_logic := ''1'';')
[void]$sb.AppendLine('        data    : in  std_logic_vector(databits-1 downto 0);')
[void]$sb.AppendLine('        wren    : in  std_logic := ''0'';')
[void]$sb.AppendLine('        q       : out std_logic_vector(databits-1 downto 0)')
[void]$sb.AppendLine('    );')
[void]$sb.AppendLine('end entity spram;')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('architecture arch of spram is')
[void]$sb.AppendLine("    constant TOTAL : integer := $total;")
[void]$sb.AppendLine('    type ram_type is array (0 to TOTAL-1) of std_logic_vector(7 downto 0);')
[void]$sb.AppendLine('    constant ROM : ram_type := (')
# Emit 16 words per line
$idx = 0
foreach ($s in $segments) {
    [void]$sb.AppendLine("        -- $($s.Mif)")
    $bytes = $data[$s.Name]
    $last = $s.Name -eq $segments[$segments.Count - 1].Name
    for ($i = 0; $i -lt $bytes.Count; $i += 16) {
        $chunk = @()
        for ($j = $i; $j -lt [Math]::Min($i + 16, $bytes.Count); $j++) {
            $chunk += ('x"{0:X2}"' -f $bytes[$j])
        }
        $line = '        ' + ($chunk -join ', ')
        if (-not ($last -and ($i + 16) -ge $bytes.Count)) { $line += ',' }
        [void]$sb.AppendLine($line)
        $idx++
    }
}
[void]$sb.AppendLine('    );')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('    impure function seg_base(f : in string) return integer is')
[void]$sb.AppendLine('    begin')
foreach ($s in $segments) {
    [void]$sb.AppendLine("        if f = ""rtl/roms/$($s.Mif)"" then")
    [void]$sb.AppendLine("            return $($offset[$s.Name]);")
    [void]$sb.AppendLine('        end if;')
}
[void]$sb.AppendLine('        report "spram_const: unknown init_file: " & f severity failure;')
[void]$sb.AppendLine('        return 0;')
[void]$sb.AppendLine('    end function seg_base;')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('    constant base : integer := seg_base(init_file);')
[void]$sb.AppendLine('    signal mem : ram_type := ROM;')
[void]$sb.AppendLine('begin')
[void]$sb.AppendLine('    assert databits = 8 report "spram_const: only 8-bit data is supported" severity failure;')
[void]$sb.AppendLine('    process (clock)')
[void]$sb.AppendLine('    begin')
[void]$sb.AppendLine('        if (clock''event and clock = ''1'') then')
[void]$sb.AppendLine('            if wren = ''1'' then')
[void]$sb.AppendLine('                mem(base + to_integer(unsigned(address))) <= data;')
[void]$sb.AppendLine('                q <= data;')
[void]$sb.AppendLine('            else')
[void]$sb.AppendLine('                q <= mem(base + to_integer(unsigned(address)));')
[void]$sb.AppendLine('            end if;')
[void]$sb.AppendLine('        end if;')
[void]$sb.AppendLine('    end process;')
[void]$sb.AppendLine('end architecture arch;')

[System.IO.File]::WriteAllText($OutFile, $sb.ToString(), (New-Object System.Text.UTF8Encoding($false)))
Write-Output "WROTE $OutFile (total=$total words, segments: video2=$($offset['video2']) keyboard=$($offset['keyboard']) apple2e=$($offset['apple2e']))"
