# Generates build/t65_rom_array.vhd from rtl/roms/apple2e.hex (16384 bytes = $F000-$FFFF).
# GHDL has no runtime file I/O, so the golden side consumes the ROM as a VHDL constant.
param()

$ErrorActionPreference = 'Stop'
$root = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
$hexPath = Join-Path $root 'rtl\roms\apple2e.hex'
$outDir = Join-Path $PSScriptRoot 'build'
$outPath = Join-Path $outDir 't65_rom_array.vhd'

New-Item -ItemType Directory -Force -Path $outDir | Out-Null

$words = @()
Get-Content $hexPath | ForEach-Object {
    foreach ($t in ($_ -split '\s+' | Where-Object { $_ })) {
        $words += [Convert]::ToByte($t, 16)
    }
}
if ($words.Count -ne 16384) { throw "apple2e.hex has $($words.Count) words, expected 16384" }

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('library ieee;')
[void]$sb.AppendLine('use ieee.std_logic_1164.all;')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('-- Generated by module_tests/t65/gen_rom_array.ps1 from rtl/roms/apple2e.hex.')
[void]$sb.AppendLine('-- Do not edit by hand; re-run the generator instead.')
[void]$sb.AppendLine('package t65_rom_array is')
[void]$sb.AppendLine('  type rom_vec_t is array (0 to 16383) of std_logic_vector(7 downto 0);')
[void]$sb.AppendLine('  constant ROM_DATA : rom_vec_t := (')
for ($i = 0; $i -lt 16384; $i += 16) {
    $line = ''
    for ($j = 0; $j -lt 16; $j++) {
        $line += ('x"{0:X2}"' -f $words[$i + $j])
        if ($j -lt 15) { $line += ', ' }
    }
    if ($i + 16 -lt 16384) { $line += ',' }
    [void]$sb.AppendLine("    $line")
}
[void]$sb.AppendLine('  );')
[void]$sb.AppendLine('end package t65_rom_array;')
[System.IO.File]::WriteAllText($outPath, $sb.ToString(), (New-Object System.Text.UTF8Encoding($false)))
Write-Host "wrote $outPath ($($words.Count) bytes)"
