// apple2_font_rom_verilog_tb.sv
//
// Cycle-equivalence testbench (candidate side) for the Verilog
// apple2_font_rom. The golden side is apple2_font_rom_vhdl_tb.vhd.
// Stimulus schedule (stim_pkg::TXN, generated by gen_stim.ps1) and CSV
// schema are IDENTICAL - see the VHDL TB header for the machine model,
// the timing convention, and the known expected write-cycle divergence.
//
// Trace (every cycle):
//   CYCLE,ROMSWITCH,ALT,LOWER,CH,ROW,IOCTL_WR,IOCTL_ADDR,IOCTL_DATA,GLYPH_DATA
// CH=%02h, ROW=%01h, IOCTL_ADDR=%04h (13 bits), IOCTL_DATA/GLYPH_DATA=%02h.

`timescale 1ns/1ps

module apple2_font_rom_verilog_tb;
   import stim_pkg::TXN;

   localparam integer TOTAL = 4228;
   localparam string TRACE_FILE = "module_tests/apple2_font_rom/build/verilog_trace.csv";

   reg         clk        = 1'b0;
   reg         romswitch  = 1'b0;
   reg         alt        = 1'b0;
   reg         lower      = 1'b0;
   reg  [6:0]  ch         = 7'h0;
   reg  [2:0]  row        = 3'h0;
   reg  [24:0] ioctl_addr = 25'h0;
   reg  [7:0]  ioctl_data = 8'h0;
   reg         ioctl_wr   = 1'b0;
   wire [7:0]  glyph_data;

   apple2_font_rom dut (
      .CLK_14M(clk),
      .ROMSWITCH(romswitch),
      .alternate_character(alt),
      .lowercase_character(lower),
      .character_code(ch),
      .glyph_row(row),
      .ioctl_addr(ioctl_addr),
      .ioctl_data(ioctl_data),
      .ioctl_wr(ioctl_wr),
      .glyph_data(glyph_data)
   );

   always #5 clk = ~clk;

   integer f;
   integer cycle;
   logic [63:0] w;

   initial begin
      f = $fopen(TRACE_FILE);
      if (f == 0) begin
         $display("FATAL: cannot open %s", TRACE_FILE);
         $finish;
      end
      $fdisplay(f, "CYCLE,ROMSWITCH,ALT,LOWER,CH,ROW,IOCTL_WR,IOCTL_ADDR,IOCTL_DATA,GLYPH_DATA");

      for (cycle = 0; cycle < TOTAL; cycle++) begin
         @(negedge clk);

         w = (cycle < 4228) ? TXN[cycle] : 64'h0;
         romswitch  = w[1];
         alt        = w[2];
         lower      = w[3];
         ch         = {w[10], w[9:4]};
         row        = w[13:11];
         ioctl_addr = {13'b0, w[26:14]};
         ioctl_data = w[34:27];
         ioctl_wr   = w[0];

         @(posedge clk);
         #1;

         $fdisplay(f, "%0d,%b,%b,%b,%02h,%01h,%b,%04h,%02h,%02h",
                   cycle, romswitch, alt, lower, ch, row, ioctl_wr,
                   ioctl_addr[12:0], ioctl_data, glyph_data);
      end

      $fclose(f);
      $finish;
   end

endmodule
