// hdd_verilog_tb.sv
//
// Cycle-equivalence testbench (candidate side) for the Verilog hdd.
// The golden side is hdd_vhdl_tb.vhd. Stimulus schedule, transaction
// table (stim_pkg::TXN, generated by gen_stim.ps1) and CSV schema are
// IDENTICAL - see the VHDL TB header for the machine model and the
// timing convention.
//
// Trace (every cycle):
//   CYCLE,D_OUT,SECTOR,HDD_READ,HDD_WRITE,RAM_DO,A,RD,IO_SELECT,
//   DEVICE_SELECT,RESET,D_IN,MOUNTED,PROTECT,RAM_ADDR,RAM_DI,RAM_WE

`timescale 1ns/1ps

module hdd_verilog_tb;
   import stim_pkg::TXN;

   localparam integer TOTAL = 6416;
   localparam string TRACE_FILE = "module_tests/hdd/build/verilog_trace.csv";

   reg         clk         = 1'b0;
   reg         io_select   = 1'b0;
   reg         dev_select  = 1'b0;
   reg         reset_sig   = 1'b1;
   reg  [15:0] a           = 16'h0;
   reg         rd          = 1'b0;
   reg  [7:0]  d_in        = 8'h0;
   wire [7:0]  d_out;
   wire [15:0] sector;
   wire        hdd_read;
   wire        hdd_write;
   reg         hdd_mounted = 1'b0;
   reg         hdd_protect = 1'b0;
   reg  [8:0]  ram_addr    = 9'h0;
   reg  [7:0]  ram_di      = 8'h0;
   wire [7:0]  ram_do;
   reg         ram_we      = 1'b0;

   hdd dut (
      .CLK_14M(clk),
      .IO_SELECT(io_select),
      .DEVICE_SELECT(dev_select),
      .RESET(reset_sig),
      .A(a),
      .RD(rd),
      .D_IN(d_in),
      .D_OUT(d_out),
      .sector(sector),
      .hdd_read(hdd_read),
      .hdd_write(hdd_write),
      .hdd_mounted(hdd_mounted),
      .hdd_protect(hdd_protect),
      .ram_addr(ram_addr),
      .ram_di(ram_di),
      .ram_do(ram_do),
      .ram_we(ram_we)
   );

   always #5 clk = ~clk;

   integer f;
   integer cycle;
   integer t;
   integer p;
   logic [63:0] w;
   logic ds;
   logic act;

   initial begin
      f = $fopen(TRACE_FILE);
      if (f == 0) begin
         $display("FATAL: cannot open %s", TRACE_FILE);
         $finish;
      end
      $fdisplay(f, "CYCLE,D_OUT,SECTOR,HDD_READ,HDD_WRITE,RAM_DO,A,RD,IO_SELECT,DEVICE_SELECT,RESET,D_IN,MOUNTED,PROTECT,RAM_ADDR,RAM_DI,RAM_WE");

      for (cycle = 0; cycle < TOTAL; cycle++) begin
         @(negedge clk);

         if (cycle < 20) begin
            reset_sig   = 1'b1;
            dev_select  = 1'b0;
            io_select   = 1'b0;
            rd          = 1'b0;
            a           = 16'h0;
            d_in        = 8'h0;
            hdd_mounted = 1'b0;
            hdd_protect = 1'b0;
            ram_we      = 1'b0;
            ram_addr    = 9'h0;
            ram_di      = 8'h0;
         end else begin
            t = (cycle - 20) / 8;
            p = (cycle - 20) % 8;
            w = (t < 797) ? TXN[t] : 64'h0;
            ds  = ((p == 0) || w[4]) && !w[5];
            // io reads are active for P=0..1: the ROM path has two
            // registered stages (rom_dout, D_OUT), so ROM[a] is only
            // visible at P=1.
            act = ds || ((p < 2) && w[5]);
            reset_sig   = (t == 791 || t == 792);
            dev_select  = ds;
            io_select   = (p < 2) && w[5];
            rd          = act && w[0];
            a           = act ? w[21:6] : 16'h0;
            d_in        = w[29:22];
            hdd_mounted = w[1];
            hdd_protect = w[2];
            ram_we      = (p == 0) && w[3];
            ram_addr    = w[38:30];
            ram_di      = w[46:39];
         end

         @(posedge clk);
         #1;

         $fdisplay(f, "%0d,%02h,%04h,%b,%b,%02h,%04h,%b,%b,%b,%b,%02h,%b,%b,%03h,%02h,%b",
                   cycle, d_out, sector, hdd_read, hdd_write, ram_do, a, rd,
                   io_select, dev_select, reset_sig, d_in, hdd_mounted,
                   hdd_protect, ram_addr, ram_di, ram_we);
      end

      $fclose(f);
      $finish;
   end

endmodule
